/* =========================================================
   SANGRAHA — ON-SCREEN TEXT (English / Français)
   ---------------------------------------------------------
   Every button, heading and message in the game is here.
   To change wording, edit the text between the quotes.
   {n}, {name}, etc. are filled in by the game: keep them as they are.
   Lines written as  v => ...  choose between singular and plural; edit
   the words inside the quotes only.
   The French uses simple tenses (présent, passé composé) and "tu".
   ========================================================= */

window.SANGRAHA_TEXT = {

  en: {
    langName: "English",
    chooseLang: "Choose your language",
    langSwitchLocked: "Finish this screen first",

    /* top bar & title */
    setLabel: "{set} Set",
    titleSub: "The {set} Set · HRT3M",
    savedGame: "Saved game: {have} of {total} cards · {rares} of {rareTotal} rare · {coins} coins",
    btnContinue: "Continue",
    btnNewGame: "New Game",
    btnStart: "Start",
    howToPlay: "How to play",
    how1: "Answer questions in rounds of {n} to earn coins.",
    how2: "Spend coins on packs of 5, 8 or 10 cards in the Pack Shop.",
    how3: "Collect all {total} cards across {sections} sections.",
    how4: "Complete a section to unlock a bonus round for its rare card.",
    howNote: "Missed questions come back later, and you never lose coins for a wrong answer.",
    confirmNewGame: "Start a new game? Your saved cards and coins will be erased.",
    confirmReset: "Reset all progress for this set? Cards and coins will be lost.",

    /* cards */
    rarePrefix: "★ Rare · ",
    clues: "Clues",
    readUpClose: "Read {name} up close",
    backToCards: "← Back to cards",
    art_symbol: "symbol", art_illustration: "illustration", art_photo: "photo", art_image: "image",

    /* packs */
    tearHere: "TEAR HERE",
    cardsCount: "{n} CARDS",
    badgeNew: "NEW",
    tapToTear: "Tap the pack to tear it open",
    tapToTearLabel: "Tap to tear open the pack",
    skip: "Skip ▸",
    rareCardClue: "★ Rare card · ",
    starterPack: "STARTER PACK",
    pack_small: "Small Pack", pack_medium: "Medium Pack", pack_large: "Large Pack",

    /* starter */
    welcome: "Welcome to the {set} Set",
    welcomeGoal: "Your goal: collect every card. Answer questions to earn coins, spend coins on packs, and complete each section to unlock its rare card.",
    welcomeFree: "Here's a free pack to get you started.",
    starterStarted: "You've started your {section} section: {got} of {n} cards. ",
    starterNext: "Earn coins by answering questions, then buy packs to find the rest.",
    firstRound: "Start your first round →",

    /* shop */
    shopTitle: "Pack Shop",
    backCollection: "← Collection",
    shopLead: "{n} cards left to collect. Most cards in a pack will be new to you, and every duplicate gives back {refund} coins.",
    shopDone: "You've collected every card in the set!",
    setComplete: "Set complete",
    buyOpen: "Buy & open",
    needMore: "Need {n} more",
    perCard: "{n} coins per card",
    earnMore: "Earn more coins: play a round",
    packOpened: "{pack} opened!",
    newCards: v => v.n + " new card" + (v.n === 1 ? "" : "s"),
    duplicates: v => " · " + v.n + " duplicate" + (v.n === 1 ? "" : "s") + " (+" + v.coins + " coins)",
    leftToCollect: " · {n} left to collect",
    setCompleteShort: " · set complete!",
    backToShop: "Back to shop",
    playRound: "Play a round",
    viewCollection: "View collection",

    /* section complete & bonus */
    sectionComplete: "{section} section complete! ",
    winRareInBonus: "Win its rare card in a bonus round.",
    bonusButton: "★ Bonus round: {section}",
    bonusReady: v => v.n === 1 ? "A bonus round is ready!" : v.n + " bonus rounds are ready!",
    bonusTag: "★ BONUS ROUND ★",
    bonusLead: "Answer {n} challenge questions about {section}. Get {need} right to win this section's rare card.",
    rareCard: "★ Rare card",
    bonusNoStakes: "No coins are at stake. If you miss it, play one more question round and try again.",
    startBonus: "Start bonus round",
    notYet: "Not yet",
    noSectionQuestions: "This section has no questions yet.",
    correctLabel: "correct",
    notThisTime: "Not this time",
    bonusFailLead: "You needed {need} correct. Play one question round to review, then the {section} bonus round opens again, with different questions where possible.",
    rareWon: "Rare card won!",
    joinsRare: " joins your rare collection · {got} of {total} rare cards",
    allRaresWon: "You've won every rare card in the set!",
    packShop: "Pack Shop",

    /* hub */
    yourCollection: "Your Collection",
    hubSummary: "{have} of {total} cards · {rares} of {rareTotal} rare cards",
    pillRounds: "Rounds: {n}",
    pillAccuracy: "Accuracy: {n}%",
    pillBest: "Best streak: {n}",
    playRoundBtn: "Play a Round ({n} questions)",
    finishBtn: "Finish & see results",
    sections: "Sections",
    resetProgress: "Reset progress",

    /* collection */
    back: "← Back",
    notCollected: "Not yet collected",
    rareLockedNone: "Complete this section and win the bonus round",
    rareLockedReady: "Win the bonus round to unlock",
    bonusLockedNote: "Play one more question round, then try the bonus round again.",
    collectedCount: "{got} of {n} cards collected",
    tapToRead: " · Tap a card to read it up close",

    /* questions */
    noQuestions: "No questions are loaded.",
    bonusPill: "★ Bonus · need {need} of {n}",
    streak: "Streak {n}",
    correctCoins: "Correct! +{n} coins",
    correctPlain: "Correct!",
    notQuite: "Not quite. This one will come back later.",
    notQuitePlain: "Not quite.",
    streakBonus: " Streak bonus +{n}!",
    seeResults: "See results",
    nextQuestion: "Next question →",
    hintMatch: "Tap an item on the left, then its match on the right.",
    hintOrder: "Tap the items in the correct order. Tap a placed item to remove it.",
    hintSort: "Tap an item, then tap the category it belongs in.",
    allSorted: "All sorted. Check your answer!",
    checkAnswer: "Check answer",
    correctAnswer: "Correct answer",
    kinds: {},   // question labels stay as written in the question file

    /* round summary */
    roundComplete: "Round complete!",
    coinsEarned: "coins earned",
    totalCoins: "total coins",
    missedComeBack: "Missed questions come back in a later round.",
    playAnother: "Play another round",

    /* results */
    stillToReview: "Still to review",
    gotItLater: "Got it right later",
    missedTimes: "missed {n}×",
    answerLabel: "Answer: ",
    noMisses: "You didn't miss a single question. Excellent work!",
    noAnswers: "No questions answered yet. Play a round first!",
    resultsKicker: "Sangraha · {set} Set · Results",
    exitTicket: "Exit Ticket",
    nameLabel: "Name: ",
    namePlaceholder: "Type your name",
    nameAria: "Your name",
    statCards: "cards collected",
    statRares: "rare cards won",
    statAnswered: "questions answered",
    statAccuracy: "accuracy",
    statBest: "best streak",
    statPacks: "packs opened",
    conceptsReview: "Concepts to review",
    handIn: "Take a screenshot, or use Print to save a PDF, and hand it in.",
    printBtn: "Print / Save PDF",
    backToGame: "Back to the game",
    dateLocale: "en-CA",

    /* teacher panel */
    tpTitle: "Teacher test panel",
    tpWarn: "For testing. Changes the save in this browser only.",
    tpSection: "Section ",
    tpClose: "Close",
    tpConfirmReset: "Erase this browser's save?",
    tp_coins500: "+500 coins",
    tp_coins2000: "+2000 coins",
    tp_complete: "Complete section",
    tp_almost: "All but 1 card in section",
    tp_almostHint: "next pack will likely complete it",
    tp_rare: "Win section's rare card",
    tp_allCards: "Unlock all cards",
    tp_allRares: "Win all rare cards",
    tp_skipWait: "Skip bonus-round wait",
    tp_sample: "Add 40 sample answers",
    tp_sampleHint: "fills the results screen",
    tp_results: "Open results screen",
    tp_reset: "Reset this save"
  },

  fr: {
    langName: "Français",
    chooseLang: "Choisis ta langue",
    langSwitchLocked: "Termine cet écran d'abord",

    setLabel: "{set}",
    titleSub: "Collection {set} · HRT3M",
    savedGame: "Partie sauvegardée : {have} cartes sur {total} · {rares} rares sur {rareTotal} · {coins} pièces",
    btnContinue: "Continuer",
    btnNewGame: "Nouvelle partie",
    btnStart: "Commencer",
    howToPlay: "Comment jouer",
    how1: "Réponds à des questions (manches de {n}) pour gagner des pièces.",
    how2: "Avec tes pièces, achète des paquets de 5, 8 ou 10 cartes à la boutique.",
    how3: "Collectionne les {total} cartes des {sections} sections.",
    how4: "Termine une section pour débloquer une manche bonus et gagner sa carte rare.",
    howNote: "Les questions ratées reviennent plus tard. Tu ne perds jamais de pièces pour une mauvaise réponse.",
    confirmNewGame: "Commencer une nouvelle partie? Tes cartes et tes pièces vont être effacées.",
    confirmReset: "Effacer toute ta progression? Tes cartes et tes pièces vont disparaître.",

    rarePrefix: "★ ",
    clues: "Indices",
    readUpClose: "Lire la carte {name} de près",
    backToCards: "← Retour aux cartes",
    art_symbol: "symbole", art_illustration: "illustration", art_photo: "photo", art_image: "image",

    tearHere: "DÉCHIRE ICI",
    cardsCount: "{n} CARTES",
    badgeNew: "NOUVEAU",
    tapToTear: "Touche le paquet pour l'ouvrir",
    tapToTearLabel: "Touche pour déchirer le paquet",
    skip: "Passer ▸",
    rareCardClue: "★ Carte rare · ",
    starterPack: "PAQUET DE DÉPART",
    pack_small: "Petit paquet", pack_medium: "Paquet moyen", pack_large: "Grand paquet",

    welcome: "Bienvenue dans la collection {set}",
    welcomeGoal: "Ton but : collectionner toutes les cartes. Réponds à des questions pour gagner des pièces, achète des paquets et termine chaque section pour débloquer sa carte rare.",
    welcomeFree: "Voici un paquet gratuit pour commencer.",
    starterStarted: "Tu as commencé ta section {section} : {got} cartes sur {n}. ",
    starterNext: "Gagne des pièces en répondant aux questions, puis achète des paquets pour trouver les autres cartes.",
    firstRound: "Commence ta première manche →",

    shopTitle: "Boutique de paquets",
    backCollection: "← Collection",
    shopLead: "Il te reste {n} cartes à trouver. La plupart des cartes d'un paquet sont nouvelles pour toi, et chaque doublon te redonne {refund} pièces.",
    shopDone: "Tu as trouvé toutes les cartes de la collection!",
    setComplete: "Collection complète",
    buyOpen: "Acheter et ouvrir",
    needMore: "Il manque {n} pièces",
    perCard: "{n} pièces par carte",
    earnMore: "Gagne plus de pièces : joue une manche",
    packOpened: "{pack} ouvert!",
    newCards: v => v.n + (v.n === 1 ? " nouvelle carte" : " nouvelles cartes"),
    duplicates: v => " · " + v.n + (v.n === 1 ? " doublon" : " doublons") + " (+" + v.coins + " pièces)",
    leftToCollect: " · il en reste {n} à trouver",
    setCompleteShort: " · collection complète!",
    backToShop: "Retour à la boutique",
    playRound: "Jouer une manche",
    viewCollection: "Voir ma collection",

    sectionComplete: "Section {section} terminée! ",
    winRareInBonus: "Gagne sa carte rare dans une manche bonus.",
    bonusButton: "★ Manche bonus : {section}",
    bonusReady: v => v.n === 1 ? "Une manche bonus est prête!" : v.n + " manches bonus sont prêtes!",
    bonusTag: "★ MANCHE BONUS ★",
    bonusLead: "Réponds à {n} questions défi sur la section {section}. Trouve {need} bonnes réponses pour gagner la carte rare de cette section.",
    rareCard: "★ Carte rare",
    bonusNoStakes: "Tu ne risques pas de pièces. Si tu rates, joue une autre manche de questions et essaie encore.",
    startBonus: "Commencer la manche bonus",
    notYet: "Pas maintenant",
    noSectionQuestions: "Cette section n'a pas encore de questions.",
    correctLabel: "bonnes réponses",
    notThisTime: "Pas cette fois",
    bonusFailLead: "Il fallait {need} bonnes réponses. Joue une manche de questions pour réviser. Ensuite, la manche bonus {section} revient, avec d'autres questions si possible.",
    rareWon: "Carte rare gagnée!",
    joinsRare: " rejoint ta collection rare · {got} cartes rares sur {total}",
    allRaresWon: "Tu as gagné toutes les cartes rares de la collection!",
    packShop: "Boutique",

    yourCollection: "Ta collection",
    hubSummary: "{have} cartes sur {total} · {rares} cartes rares sur {rareTotal}",
    pillRounds: "Manches : {n}",
    pillAccuracy: "Réussite : {n} %",
    pillBest: "Meilleure série : {n}",
    playRoundBtn: "Jouer une manche ({n} questions)",
    finishBtn: "Terminer et voir mes résultats",
    sections: "Sections",
    resetProgress: "Effacer ma progression",

    back: "← Retour",
    notCollected: "Pas encore trouvée",
    rareLockedNone: "Termine cette section et gagne la manche bonus",
    rareLockedReady: "Gagne la manche bonus pour la débloquer",
    bonusLockedNote: "Joue encore une manche de questions, puis essaie la manche bonus de nouveau.",
    collectedCount: "{got} cartes sur {n} trouvées",
    tapToRead: " · Touche une carte pour la lire de près",

    noQuestions: "Aucune question n'est chargée.",
    bonusPill: "★ Bonus · il faut {need} sur {n}",
    streak: "Série {n}",
    correctCoins: "Bonne réponse! +{n} pièces",
    correctPlain: "Bonne réponse!",
    notQuite: "Pas tout à fait. Cette question va revenir plus tard.",
    notQuitePlain: "Pas tout à fait.",
    streakBonus: " Bonus de série +{n}!",
    seeResults: "Voir les résultats",
    nextQuestion: "Question suivante →",
    hintMatch: "Touche un élément à gauche, puis la bonne réponse à droite.",
    hintOrder: "Touche les éléments dans le bon ordre. Touche un élément placé pour l'enlever.",
    hintSort: "Touche un élément, puis touche la bonne catégorie.",
    allSorted: "Tout est classé. Vérifie ta réponse!",
    checkAnswer: "Vérifier",
    correctAnswer: "La bonne réponse",
    kinds: {
      "Definition": "Définition", "Concept": "Concept", "Scenario": "Mise en situation",
      "Iconography": "Iconographie", "Match": "Associer", "Odd One Out": "L'intrus",
      "Fill the Gap": "Texte à trous", "Connection": "Lien", "Timeline": "Ligne du temps",
      "Story": "Récit", "Place": "Lieu", "Text to Idea": "Du texte à l'idée", "Sort": "Classer",
      "Cause & Effect": "Cause et effet", "Life Cycle": "Cycle de vie", "Symbol": "Symbole",
      "Sequence": "Séquence"
    },

    roundComplete: "Manche terminée!",
    coinsEarned: "pièces gagnées",
    totalCoins: "pièces en tout",
    missedComeBack: "Les questions ratées reviennent dans une autre manche.",
    playAnother: "Jouer une autre manche",

    stillToReview: "À réviser",
    gotItLater: "Réussie plus tard",
    missedTimes: "ratée {n} fois",
    answerLabel: "Réponse : ",
    noMisses: "Tu n'as raté aucune question. Excellent travail!",
    noAnswers: "Tu n'as pas encore répondu à des questions. Joue d'abord une manche!",
    resultsKicker: "Sangraha · {set} · Résultats",
    exitTicket: "Billet de sortie",
    nameLabel: "Nom : ",
    namePlaceholder: "Écris ton nom",
    nameAria: "Ton nom",
    statCards: "cartes trouvées",
    statRares: "cartes rares gagnées",
    statAnswered: "questions répondues",
    statAccuracy: "réussite",
    statBest: "meilleure série",
    statPacks: "paquets ouverts",
    conceptsReview: "Concepts à réviser",
    handIn: "Prends une capture d'écran ou utilise Imprimer pour enregistrer un PDF, puis remets-le.",
    printBtn: "Imprimer / PDF",
    backToGame: "Retour au jeu",
    dateLocale: "fr-CA",

    tpTitle: "Panneau de test (enseignant)",
    tpWarn: "Pour les tests. Change la sauvegarde de ce navigateur seulement.",
    tpSection: "Section ",
    tpClose: "Fermer",
    tpConfirmReset: "Effacer la sauvegarde de ce navigateur?",
    tp_coins500: "+500 pièces",
    tp_coins2000: "+2000 pièces",
    tp_complete: "Compléter la section",
    tp_almost: "Section moins 1 carte",
    tp_almostHint: "le prochain paquet va sûrement la compléter",
    tp_rare: "Gagner la carte rare",
    tp_allCards: "Débloquer toutes les cartes",
    tp_allRares: "Gagner toutes les cartes rares",
    tp_skipWait: "Annuler l'attente bonus",
    tp_sample: "Ajouter 40 réponses test",
    tp_sampleHint: "remplit l'écran des résultats",
    tp_results: "Ouvrir les résultats",
    tp_reset: "Effacer cette sauvegarde"
  }
};
